sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.sylius_payment':
            paymob_form:
                template: '@AhmedkhdSyliusPaymobPlugin/admin/payment_method/form/paymob_form.html.twig'
                priority: 0
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.sylius_payment':
            paymob_form:
                template: '@AhmedkhdSyliusPaymobPlugin/admin/payment_method/form/paymob_form.html.twig'
                priority: 0