services:
  # Gateway Factory
  ahmedkhd.sylius_paymob_plugin.gateway_factory:
    class: Ahmedkhd\SyliusPaymobPlugin\Factory\PaymobGatewayFactory
    tags:
      - { name: sylius.payment.gateway_factory, type: paymob }

  # Gateway Configuration Type
  Ahmedkhd\SyliusPaymobPlugin\Form\Type\SyliusGatewayConfigurationType:
    tags:
      - { name: sylius.gateway_configuration_type, type: paymob, label: "Paymob Payment" }
      - { name: form.type }

  # Payment Request Command Provider
  ahmedkhd.sylius_paymob_plugin.provider.payment_request.command.capture:
    class: Ahmedkhd\SyliusPaymobPlugin\Provider\CaptureCommandProvider
    tags:
      - name: sylius.payment_request.provider.command
        gateway_factory: paymob
        action: capture

  # Payment Request Command Handler
  ahmedkhd.sylius_paymob_plugin.command_handler.capture:
    class: Ahmedkhd\SyliusPaymobPlugin\CommandHandler\CapturePaymentCommandHandler
    tags:
      - { name: messenger.message_handler }

  # Payment Request HTTP Response Provider
  ahmedkhd.sylius_paymob_plugin.provider.payment_request.http_response.capture:
    class: Ahmedkhd\SyliusPaymobPlugin\Provider\CaptureHttpResponseProvider
    tags:
      - name: sylius.payment_request.provider.http_response
        gateway_factory: paymob
        action: capture

  # Paymob Service
  ahmedkhd.sylius_paymob_plugin.service.paymob:
    class: Ahmedkhd\SyliusPaymobPlugin\Services\PaymobService
    public: true
    arguments:
      - '@service_container'
      - '@sylius.repository.payment'

  # Notify Controller
  Ahmedkhd\SyliusPaymobPlugin\Controller\NotifyController:
    public: true
    autowire: true
    arguments:
      - '@ahmedkhd.sylius_paymob_plugin.service.paymob'
