imports:
  - { resource: "services.yml" }

sylius_payment:
  gateway_config:
    validation_groups:
      paymob:
        - sylius
        - paymob

sylius_twig_hooks:
  hooks:
    'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.paymob':
      configuration:
        template: '@AhmedkhdSyliusPaymobPlugin/admin/payment_method/form/paymob_configuration.html.twig'
        priority: 0
